THEMES = {
    "corporate_blue": {
        "header_fill":   "1B3A5C",
        "header_font":   "FFFFFF",
        "accent_light":  "E9EFF5",
        "accent_medium": "C5D5E8",
        "border_dark":   "1B3A5C",
        "border_light":  "B0C4D8",
        "tab_color":     "1B3A5C",
        "total_fill":    "D4E1EE",
        "total_font":    "1B3A5C",
    },
    "executive_gray": {
        "header_fill":   "2D2D2D",
        "header_font":   "FFFFFF",
        "accent_light":  "F2F2F2",
        "accent_medium": "E0E0E0",
        "border_dark":   "2D2D2D",
        "border_light":  "BDBDBD",
        "tab_color":     "2D2D2D",
        "total_fill":    "E0E0E0",
        "total_font":    "2D2D2D",
    },
    "forest_green": {
        "header_fill":   "1B5E20",
        "header_font":   "FFFFFF",
        "accent_light":  "E8F5E9",
        "accent_medium": "C8E6C9",
        "border_dark":   "1B5E20",
        "border_light":  "A5D6A7",
        "tab_color":     "1B5E20",
        "total_fill":    "C8E6C9",
        "total_font":    "1B5E20",
    },
    "burgundy": {
        "header_fill":   "6E1423",
        "header_font":   "FFFFFF",
        "accent_light":  "FBEAEE",
        "accent_medium": "F0C6CF",
        "border_dark":   "6E1423",
        "border_light":  "D4929E",
        "tab_color":     "6E1423",
        "total_fill":    "F0C6CF",
        "total_font":    "6E1423",
    },
    "navy_gold": {
        "header_fill":   "0D1B2A",
        "header_font":   "E8C547",
        "accent_light":  "EFF1F3",
        "accent_medium": "D3D9E0",
        "border_dark":   "0D1B2A",
        "border_light":  "8B9DAF",
        "tab_color":     "0D1B2A",
        "total_fill":    "D3D9E0",
        "total_font":    "0D1B2A",
    },
    "teal_modern": {
        "header_fill":   "00565B",
        "header_font":   "FFFFFF",
        "accent_light":  "E0F2F1",
        "accent_medium": "B2DFDB",
        "border_dark":   "00565B",
        "border_light":  "80CBC4",
        "tab_color":     "00565B",
        "total_fill":    "B2DFDB",
        "total_font":    "00565B",
    },
    "slate_purple": {
        "header_fill":   "4A148C",
        "header_font":   "FFFFFF",
        "accent_light":  "F3E5F5",
        "accent_medium": "E1BEE7",
        "border_dark":   "4A148C",
        "border_light":  "BA68C8",
        "tab_color":     "4A148C",
        "total_fill":    "E1BEE7",
        "total_font":    "4A148C",
    },
}

NUMBER_FORMATS = {
    "integer":       "#,##0",
    "decimal_1":     "#,##0.0",
    "decimal_2":     "#,##0.00",
    "decimal_3":     "#,##0.000",
    "percentage":    "0.00%",
    "percentage_0":  "0%",
    "currency_usd":  "$#,##0.00",
    "currency_eur":  "€#,##0.00",
    "currency_gbp":  "£#,##0.00",
    "currency_inr":  "₹#,##0.00",
    "date_ymd":      "YYYY-MM-DD",
    "date_mdy":      "MM/DD/YYYY",
    "date_dmy":      "DD/MM/YYYY",
    "date_long":     "MMMM D, YYYY",
    "time_hm":       "HH:MM",
    "time_hms":      "HH:MM:SS",
    "accounting":    '_($* #,##0.00_);_($* (#,##0.00);_($* "-"??_);_(@_)',
    "text":          "@",
    "general":       "General",
    "id":            "0",
}

ALIGNMENTS = ["left", "center", "right"]
